FROM almalinux:9
LABEL author="raidi kartheek" \
      company="joindevops" \       
      topic="docker" \
      duration="2hrs"

# TO filter the labels 
#docker image -f label=company=joindevops 
# this will filter the labels