# ARG version
# FROM almalinux:${version}:-9}
# ARG course="DevOps with AWS" \
#     duration="120hrs" 
# #access ARG values inside container.
# #set arg values to env variables.
# ENV duration=$duration 
# RUN echo "course:$course,duration:$duration" 
# CMD ["sleep","100"]
#ARG version
FROM  almalinux:9
ARG name = "raidi"\
    course = "devops"
RUN echo "course:$course,name:$name
CMD ["sleep","100"] 