ARG version
FROM almalinux:${version:-9}
ARG name="raidi" \
    interview_on="devops" 
#access ARG values inside container.
#set arg values to env variables.
ENV interview_on=$interview_on 
RUN echo "name: $name,interview: $interview_on,version: $version" 
CMD ["sleep","100"]
