ARG version
FROM almalinux:${version}:-9}
ARG name="raidi" \
    interview_on="devops" 
#access ARG values inside container.
#set arg values to env variables.
ENV duration=$duration 
RUN echo "name:$name,interview:$interview_on" 
CMD ["sleep","100"]
