FROM almalinux:9
RUN dnf install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
ADD  /usr/share/nginx/html/index.html    
CMD ["nginx", "-g", "daemon off;"]
# it can get files from internet and store usr/share/nginx/html/index.html